coverage:
  status:
    project:
      default: false
    patch:
      default: false
      python:
        paths:
        - "src/sentry"
        target: 90%
  ignore:
  - src/sentry/lint/.*
  - src/sentry/runner/.*
  - src/.*?/migrations/.*
  - src/.*?/south_migrations/.*
comment: false
